import type { Patient } from '@shared/types/patient';

export const mockPatients: Patient[] = [
  {
    id: 'p001',
    name: 'Aanya Sharma',
    age: 34,
    gender: 'female',
    status: 'active',
    condition: 'Hypertension',
    lastVisit: '2026-04-28',
    doctor: 'Dr. Kapoor',
  },
  {
    id: 'p002',
    name: 'Rohan Mehta',
    age: 58,
    gender: 'male',
    status: 'critical',
    condition: 'Cardiac arrhythmia',
    lastVisit: '2026-05-01',
    doctor: 'Dr. Iyer',
  },
  {
    id: 'p003',
    name: 'Priya Iyer',
    age: 29,
    gender: 'female',
    status: 'active',
    condition: 'Type 2 diabetes',
    lastVisit: '2026-04-22',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p004',
    name: 'Vikram Singh',
    age: 45,
    gender: 'male',
    status: 'follow-up',
    condition: 'Post-op recovery',
    lastVisit: '2026-04-15',
    doctor: 'Dr. Reddy',
  },
  {
    id: 'p005',
    name: 'Sara Khan',
    age: 38,
    gender: 'female',
    status: 'discharged',
    condition: 'Knee replacement',
    lastVisit: '2026-04-30',
    doctor: 'Dr. Reddy',
  },
  {
    id: 'p006',
    name: 'Aarav Reddy',
    age: 7,
    gender: 'male',
    status: 'active',
    condition: 'Asthma',
    lastVisit: '2026-04-29',
    doctor: 'Dr. Pillai',
  },
  {
    id: 'p007',
    name: 'Neha Kapoor',
    age: 52,
    gender: 'female',
    status: 'follow-up',
    condition: 'Migraine',
    lastVisit: '2026-04-18',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p008',
    name: 'Arjun Nair',
    age: 41,
    gender: 'male',
    status: 'active',
    condition: 'Lower back pain',
    lastVisit: '2026-04-25',
    doctor: 'Dr. Reddy',
  },
  {
    id: 'p009',
    name: 'Isha Verma',
    age: 26,
    gender: 'female',
    status: 'critical',
    condition: 'Severe pneumonia',
    lastVisit: '2026-05-01',
    doctor: 'Dr. Pillai',
  },
  {
    id: 'p010',
    name: 'Karan Malhotra',
    age: 63,
    gender: 'male',
    status: 'follow-up',
    condition: 'Post-MI care',
    lastVisit: '2026-04-20',
    doctor: 'Dr. Iyer',
  },
  {
    id: 'p011',
    name: 'Meera Joshi',
    age: 35,
    gender: 'female',
    status: 'active',
    condition: 'Anxiety disorder',
    lastVisit: '2026-04-26',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p012',
    name: 'Dev Patel',
    age: 22,
    gender: 'male',
    status: 'discharged',
    condition: 'Appendectomy',
    lastVisit: '2026-04-12',
    doctor: 'Dr. Reddy',
  },
  {
    id: 'p013',
    name: 'Riya Bose',
    age: 48,
    gender: 'female',
    status: 'active',
    condition: 'Hypothyroidism',
    lastVisit: '2026-04-27',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p014',
    name: 'Aditya Rao',
    age: 31,
    gender: 'male',
    status: 'active',
    condition: 'Allergic rhinitis',
    lastVisit: '2026-04-24',
    doctor: 'Dr. Pillai',
  },
  {
    id: 'p015',
    name: 'Tara Desai',
    age: 56,
    gender: 'female',
    status: 'critical',
    condition: 'Sepsis',
    lastVisit: '2026-05-01',
    doctor: 'Dr. Iyer',
  },
  {
    id: 'p016',
    name: 'Omar Sheikh',
    age: 39,
    gender: 'male',
    status: 'follow-up',
    condition: 'Fractured tibia',
    lastVisit: '2026-04-19',
    doctor: 'Dr. Reddy',
  },
  {
    id: 'p017',
    name: 'Lakshmi Pillai',
    age: 67,
    gender: 'female',
    status: 'active',
    condition: 'Osteoarthritis',
    lastVisit: '2026-04-23',
    doctor: 'Dr. Reddy',
  },
  {
    id: 'p018',
    name: 'Ravi Shankar',
    age: 50,
    gender: 'male',
    status: 'discharged',
    condition: 'Gallbladder removal',
    lastVisit: '2026-04-10',
    doctor: 'Dr. Reddy',
  },
  {
    id: 'p019',
    name: 'Nisha Agarwal',
    age: 28,
    gender: 'female',
    status: 'active',
    condition: 'PCOS',
    lastVisit: '2026-04-21',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p020',
    name: 'Sameer Khanna',
    age: 44,
    gender: 'male',
    status: 'follow-up',
    condition: 'Hypertension',
    lastVisit: '2026-04-17',
    doctor: 'Dr. Kapoor',
  },
  {
    id: 'p021',
    name: 'Pooja Ramesh',
    age: 33,
    gender: 'female',
    status: 'active',
    condition: 'Iron deficiency',
    lastVisit: '2026-04-26',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p022',
    name: 'Faisal Ahmed',
    age: 60,
    gender: 'male',
    status: 'critical',
    condition: 'Acute MI',
    lastVisit: '2026-05-01',
    doctor: 'Dr. Iyer',
  },
  {
    id: 'p023',
    name: 'Anjali Menon',
    age: 19,
    gender: 'female',
    status: 'active',
    condition: 'Eczema',
    lastVisit: '2026-04-22',
    doctor: 'Dr. Pillai',
  },
  {
    id: 'p024',
    name: 'Yash Bhatia',
    age: 36,
    gender: 'male',
    status: 'follow-up',
    condition: 'Concussion',
    lastVisit: '2026-04-16',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p025',
    name: 'Divya Krishnan',
    age: 42,
    gender: 'female',
    status: 'active',
    condition: 'Asthma',
    lastVisit: '2026-04-28',
    doctor: 'Dr. Pillai',
  },
  {
    id: 'p026',
    name: 'Manish Gupta',
    age: 55,
    gender: 'male',
    status: 'discharged',
    condition: 'Hernia repair',
    lastVisit: '2026-04-08',
    doctor: 'Dr. Reddy',
  },
  {
    id: 'p027',
    name: 'Kavya Subramanian',
    age: 24,
    gender: 'female',
    status: 'active',
    condition: 'Sinusitis',
    lastVisit: '2026-04-25',
    doctor: 'Dr. Pillai',
  },
  {
    id: 'p028',
    name: 'Imran Qureshi',
    age: 47,
    gender: 'male',
    status: 'follow-up',
    condition: 'Diabetic foot',
    lastVisit: '2026-04-14',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p029',
    name: 'Sneha Pandey',
    age: 30,
    gender: 'female',
    status: 'active',
    condition: 'Migraine',
    lastVisit: '2026-04-29',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p030',
    name: 'Rajesh Iyer',
    age: 71,
    gender: 'male',
    status: 'critical',
    condition: 'Stroke',
    lastVisit: '2026-05-01',
    doctor: 'Dr. Iyer',
  },
  {
    id: 'p031',
    name: "Tanya D'Souza",
    age: 27,
    gender: 'female',
    status: 'active',
    condition: 'UTI',
    lastVisit: '2026-04-27',
    doctor: 'Dr. Banerjee',
  },
  {
    id: 'p032',
    name: 'Ankit Saxena',
    age: 38,
    gender: 'male',
    status: 'follow-up',
    condition: 'Tendonitis',
    lastVisit: '2026-04-13',
    doctor: 'Dr. Reddy',
  },
];
